name: smart_doku
description: "A new Flutter project."
publish_to: '' # Remove this line if you wish to publish to pub.dev

version: 0.8.10+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  flutter_animate: ^4.5.2
  dropdown_button2: ^2.3.9
  font_awesome_flutter: ^10.5.0
  line_icons: ^2.0.3
  package_info_plus: ^9.0.0
  file_picker: ^10.2.0
  image_picker_windows: ^0.2.1+1
  connectivity_plus: ^6.0.3
  flutter_localizations: 
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  window_size: ^0.1.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  http: ^1.4.0
  multi_select_flutter: ^4.1.3
  path: ^1.9.1
  path_provider: ^2.1.5
  collection: ^1.19.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .config/.env
    - images/background_images.jpg
    - images/Icon_App.png
    - images/LogoKabupatenMalang.png
    - images/smartdoku_logo.jpeg
    - images/logoApp.jpg
    - images/logoApps.png

  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: fonts/times/times.ttf
          style: normal
        - asset: fonts/times/timesbd.ttf
          weight: 700
        - asset: fonts/times/timesi.ttf
          style: italic
        - asset: fonts/times/timesbi.ttf
          weight: 700
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logoApps.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/logoApps.png"